### test no version
###   fixture for ConfigSchemaGameTest#migrateConfigParsePaths
### deliberately omits config_version
### this disables ADConfig version machinery
test_no_version_marker=true
another_test_key=42
mixed_case_default=MiXeD
